services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - WATCHDOG_TIMEOUT=10
      - PYTHONPATH=/app/src
    command: streamlit run src/main.py --server.runOnSave=true
    tty: true
